# Generated by Django 3.0.2 on 2020-01-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_pict', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
