# Generated by Django 3.0.2 on 2020-01-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_pict', '0004_auto_20200128_0110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
