# Generated by Django 3.0.2 on 2020-01-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_pict', '0006_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
